# Generated by Django 5.1.6 on 2025-03-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='online_courses.course'),
        ),
    ]
