# Generated by Django 5.1.6 on 2025-03-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0002_remove_module_description_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['course', 'order']},
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
