# Generated by Django 5.1.6 on 2025-02-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0003_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(default=None, help_text='Варианты ответов через запятую'),
            preserve_default=False,
        ),
    ]
