# Generated by Django 5.1.6 on 2025-03-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0003_alter_module_options_alter_homework_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='lesson',
        ),
        migrations.AddField(
            model_name='homework',
            name='assigned_by',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='online_courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='due_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
