# Generated by Django 5.1.6 on 2025-03-04 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0004_remove_homework_lesson_homework_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
