# Generated by Django 5.1.6 on 2025-02-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0004_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='online_courses.quiz'),
            preserve_default=False,
        ),
    ]
