# Generated by Django 5.1.6 on 2025-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0005_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
