# Generated by Django 5.1.6 on 2025-04-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0010_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
    ]
